
"""
Django settings for sukhithTproj project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-lviqoq1))jf3mlv@rw35i(a1y(7e-uot#!y6hs(4$d7ay01%!es$'
with open(os.path.join(BASE_DIR,'secret_key.txt')) as f:
     SECRET_KEY=f.read().strip()
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['www.sukhithtech.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Home',
    'Header',
    'Menus',
    'Footer',
    'Team',
    'Clients',
    'Contact',
    'Services',
    'Trainings',
    'User',
    'payment',
    'pdf',
    



  

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sukhithTproj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sukhithTproj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
       # 'ENGINE': 'django.db.backends.sqlite3',
         'ENGINE': 'django.db.backends.mysql',          
         'NAME': 'dbmaster',
	 'HOST':'ls-b5f9f985ab5744a6c0d31f2e5ec6280c7e43a534.c8mjjj0dn5xv.ap-south-1.rds.amazonaws.com',
	 'USER':'dbmasteruser',
 	 'PASSWORD':'rC>SP}XPT6E53#xVSY%ptz`C6j51Q`Y2',
	 'PORT':'3306',
	}
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT=os.path.join(BASE_DIR, 'static')
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
LOGIN_REDIRECT_URL = 'home'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

with open(os.path.join(BASE_DIR,'mailAppPW.txt'))as f:
     EMAIL_HOST_PASSWORD=f.read().strip()

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sukhithtechnologies@gmail.com'
DEFAULT_FROM_EMAIL = 'sukhithtechnologies@gmail.com'

PAYPAL_RECEIVER_EMAIL = 'sukhithtechnologies@gmail.com'
PAYPAL_TEST = True

with open(os.path.join(BASE_DIR,'razor_apikey.txt'))as f:
     RAZORPAY_API_KEY=f.read().strip()
with open(os.path.join(BASE_DIR,'razor_secretkey.txt'))as f:
     RAZORPAY_API_SECRET_KEY=f.read().strip()


#RAZORPAY_API_KEY ='rzp_test_aUa4nP2jSsrKVQ'
#RAZORPAY_API_SECRET_KEY ='JrJYnF28Lau7fjkOSxajFlNJ'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

SESSION_COOKIE_AGE = 2*60

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
