# Generated by Django 3.2.13 on 2022-07-12 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainingsch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainingcode', models.IntegerField(default=0)),
                ('Trainingtitle', models.CharField(max_length=200)),
                ('Trainingduration', models.IntegerField(default=0)),
                ('Trainingstart', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Trainingend', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Trainingvacancy', models.IntegerField(default=0)),
                ('Trainingreq', models.BooleanField(default=False)),
                ('Trainingcost', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('TransID', models.CharField(default='', max_length=25)),
                ('PaymentID', models.CharField(default='', max_length=100)),
                ('RequestedTrainings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Trainings.trainingsch')),
            ],
        ),
    ]
