# Generated by Django 3.2.13 on 2022-08-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Requesteduser',
            field=models.CharField(default='', max_length=100),
        ),
    ]
